<?php

declare(strict_types=1);

namespace App;

/**
 * Single-password admin authentication.
 *
 * - Stores nothing in a DB. Verifies submitted password against the bcrypt
 *   hash in ADMIN_PASSWORD_HASH env.
 * - Session cookie hardened: HttpOnly, SameSite=Lax, Secure when configured.
 * - On successful login regenerates the session ID to prevent fixation.
 * - On failure adds a 500ms delay so brute-force is rate-limited without
 *   needing extra infrastructure for a single-writer blog.
 */
final class Auth
{
    private static bool $started = false;

    public static function start(): void
    {
        if (self::$started || session_status() === PHP_SESSION_ACTIVE) {
            self::$started = true;
            return;
        }

        // strict_mode: reject session IDs not generated by us, forcing the
        // server to issue a fresh one if a client presents an unknown id.
        //   Defends against session fixation attempts where an attacker
        //   tries to seed a victim's browser with a known SID.
        // use_only_cookies: never accept the SID from URL parameters.
        ini_set('session.use_strict_mode', '1');
        ini_set('session.use_only_cookies', '1');

        $name = (string) Config::get('SESSION_NAME', 'lazyblog_sess');
        $secure = strtolower((string) Config::get('SESSION_SECURE', 'false')) === 'true';

        // In HTTPS mode, prepend the `__Host-` cookie prefix. Browsers
        // enforce: cookie MUST be `Secure`, path=`/`, no `Domain` attribute.
        // That bans subdomain takeover or path-narrowed shadowing — a
        // stronger guarantee than the bare `Secure` flag alone.
        if ($secure && !str_starts_with($name, '__Host-')) {
            $name = '__Host-' . $name;
        }

        session_name($name);
        session_set_cookie_params([
            'lifetime' => 0,
            'path' => '/',
            'secure' => $secure,
            'httponly' => true,
            'samesite' => 'Lax',
        ]);
        session_start();
        self::$started = true;
    }

    public static function attempt(string $password): bool
    {
        self::start();

        // Per-IP brute-force throttle — sliding 15-min window. After 10
        // failures from one IP, all subsequent attempts return false fast
        // for 15 minutes regardless of the password. Backed by a small
        // JSON file in the system temp dir (single-server scope; for
        // multi-host setups put it on shared storage or swap for Redis).
        $ip = self::clientIp();
        if (self::tooManyFailures($ip)) {
            usleep(500_000);
            return false;
        }

        $hash = (string) Config::get('ADMIN_PASSWORD_HASH', '');
        if ($hash === '') {
            // Soft fail: no hash configured yet — still burn time so callers
            // can't distinguish "no admin set" from "wrong password".
            usleep(500_000);
            self::recordFailure($ip);
            return false;
        }

        if (!password_verify($password, $hash)) {
            usleep(500_000);
            self::recordFailure($ip);
            return false;
        }

        // Successful login — drop the per-IP failure record so legitimate
        // sessions don't carry a strike count after a typo.
        self::clearFailures($ip);
        session_regenerate_id(true);
        // Rotate the CSRF token too so any pre-login captured token is
        // invalidated. Next Csrf::token() call regenerates lazily.
        unset($_SESSION[Csrf::SESSION_KEY]);
        $_SESSION['admin'] = true;
        $_SESSION['admin_since'] = time();
        return true;
    }

    private const RATE_LIMIT_FILE = '/tmp/lazyblog-login-attempts.json';
    private const RATE_LIMIT_MAX = 10;
    private const RATE_LIMIT_WINDOW_SEC = 900;  // 15 minutes

    private static function clientIp(): string
    {
        // REMOTE_ADDR is the only IP source we trust by default. If you put
        // LazyBlog behind a reverse proxy that sets X-Forwarded-For, swap
        // this for a header-aware lookup that strictly validates the proxy.
        return (string) ($_SERVER['REMOTE_ADDR'] ?? 'unknown');
    }

    /** @return array<string,list<int>> */
    private static function loadAttempts(): array
    {
        if (!is_file(self::RATE_LIMIT_FILE)) {
            return [];
        }
        $raw = @file_get_contents(self::RATE_LIMIT_FILE);
        if (!is_string($raw) || $raw === '') {
            return [];
        }
        $decoded = json_decode($raw, true);
        return is_array($decoded) ? $decoded : [];
    }

    /** @param array<string,list<int>> $attempts */
    private static function saveAttempts(array $attempts): void
    {
        @file_put_contents(self::RATE_LIMIT_FILE, (string) json_encode($attempts), LOCK_EX);
    }

    private static function tooManyFailures(string $ip): bool
    {
        $attempts = self::loadAttempts();
        $timestamps = $attempts[$ip] ?? [];
        $cutoff = time() - self::RATE_LIMIT_WINDOW_SEC;
        $recent = array_values(array_filter($timestamps, static fn (int $t): bool => $t > $cutoff));
        return count($recent) >= self::RATE_LIMIT_MAX;
    }

    private static function recordFailure(string $ip): void
    {
        $attempts = self::loadAttempts();
        $cutoff = time() - self::RATE_LIMIT_WINDOW_SEC;
        $timestamps = $attempts[$ip] ?? [];
        $timestamps = array_values(array_filter($timestamps, static fn (int $t): bool => $t > $cutoff));
        $timestamps[] = time();
        $attempts[$ip] = $timestamps;
        // Prune IPs whose latest attempt is also outside the window so the
        // file doesn't grow unbounded.
        foreach ($attempts as $key => $ts) {
            if (max($ts) <= $cutoff) {
                unset($attempts[$key]);
            }
        }
        self::saveAttempts($attempts);
    }

    private static function clearFailures(string $ip): void
    {
        $attempts = self::loadAttempts();
        if (isset($attempts[$ip])) {
            unset($attempts[$ip]);
            self::saveAttempts($attempts);
        }
    }

    public static function check(): bool
    {
        self::start();
        return !empty($_SESSION['admin']);
    }

    public static function logout(): void
    {
        self::start();
        $_SESSION = [];
        if (ini_get('session.use_cookies')) {
            $params = session_get_cookie_params();
            setcookie(
                session_name(),
                '',
                [
                    'expires' => time() - 42_000,
                    'path' => $params['path'],
                    'domain' => $params['domain'],
                    'secure' => $params['secure'],
                    'httponly' => $params['httponly'],
                    'samesite' => $params['samesite'],
                ],
            );
        }
        session_destroy();
    }

    /**
     * Guard an admin handler. If not authed, redirect to login preserving
     * the original destination in `?next=` so the user lands back where they
     * tried to go — but only when the URI looks like a sane internal path
     * (starts with `/`, no `//`, no CRLF/control chars). Anything else is
     * dropped and the user lands at /admin after login. REQUEST_URI is
     * attacker-controlled on the first request line, so pre-validating it
     * here closes the open-redirect window cleanly.
     */
    public static function requireAuth(): void
    {
        if (self::check()) {
            return;
        }
        $uri = (string) ($_SERVER['REQUEST_URI'] ?? '');
        $safe = $uri !== ''
            && $uri[0] === '/'
            && !str_starts_with($uri, '//')
            && !preg_match('/[\r\n\t\0]/', $uri);
        if ($safe) {
            Http::redirect('/admin/login?next=' . rawurlencode($uri));
        }
        Http::redirect('/admin/login');
    }
}
